### ISSUE TITLE
Memory leak HTMLElement#text and HTMLElement#rawText

### ISSUE THREAD

**Issue by ergcode** [taoqf/node-html-parser#106] opened 2021-03-20 03:24 UTC
Hey!
A strange problem occurred [https://youtu.be/TJSj7k4pyHo](https://youtu.be/TJSj7k4pyHo)

I get the text from the element using "node-html-parser" and then pass it to the object.
```js
const root = HTMLParser.parse(content);
let name = root.querySelector(`element`);
```

If I receive the text directly, then it leads to a memory leak (example in the video, the memory will grow until it leads to an error).
```js
name = name.text;
```

But if I do the "cloning" then the RAM consumption will be normal.
```js
name = JSON.parse(JSON.stringify(name.text));
```

**Comment by taoqf** [comment] 2021-03-21 10:21
Sorry I could not get access to youtu.be because of my gov is blocking me.
Maybe it is the same reason as https://github.com/taoqf/node-html-parser/issues/64
Could you pls provide some html so that I could help find the reason.

**Comment by ergcode** [comment] 2021-03-21 11:47
Example file: [view-source_https___epicentrk.ua_shop_kirpich-ogneupornyy_.zip](https://github.com/taoqf/node-html-parser/files/6177282/view-source_https___epicentrk.ua_shop_kirpich-ogneupornyy_.zip)
Link for example: https://epicentrk.ua/shop/kirpich-ogneupornyy/
Video with memory leak (8.4Mb): https://user-images.githubusercontent.com/23062770/111903066-6962d180-8a51-11eb-8d31-dfc2cc84be15.mp4 
The video in which the variable is cloned (7.9Mb): https://user-images.githubusercontent.com/23062770/111903133-c5c5f100-8a51-11eb-8214-8052a15f4295.mp4


I create an object available for visibility in all functions of this file.
```JS
const cat = {};
```

After requesting the page, I pass in "node-html-parser" the text from "content". And trying to get the text for the "name" variable.
```JS
		let root = HTMLParser.parse(content);
		let name;
		try {
			name = root.querySelector(`.shop-categories__title`);
			if (!name) name = root.querySelector(`.headList h1`);
			name = JSON.parse(JSON.stringify(name.text)).trim();
			// name = name.text.trim();
		} catch (error) { console.error(error); }

		if (!name) {
			console.error(`not found name`);
		}
```

I get the key "parent" and "lang" and, if necessary, create a new entry in "cat".
Then I put there the key and the "name" value for the desired language.
```JS
		if (!cat[parent]) cat[parent] = {
			name: {},
		};
		cat[parent][`name`][lang] = name;
```

I may be wrong, but maybe "node-html-parser" binds some functions to a text variable? And for this reason, the garbage collector cannot clear the memory.

**Comment by hedgehog90** [comment] 2021-03-21 22:47
I can confirm there is a serious memory leak issue. After several hours of using this in my app the memory consumption grows and grows, until my simple web scraping script is occupying over a gigabyte in memory.

**Comment by taoqf** [comment] 2021-03-22 03:08
It is really strange, I did some tests with your file, and could not find any clue at all.

**Comment by taoqf** [comment] 2021-03-22 03:09
https://github.com/taoqf/node-html-parser/commit/8096749b4277dd67ed9d1353a3a3f7f8cd649506

**Comment by ergcode** [comment] 2021-03-22 11:22
I redid your example to reproduce the error.
`const cat = {};` I have moved to the general scope. Now the data in this variable will accumulate. Previously, they were removed with each new cycle.

```JS
const fs = require(`fs`);
const HTMLParser = require(`node-html-parser`);

const cat = {};
const lang = 'en';

(async () => {
	const content = fs.readFileSync(`./view-source_https___epicentrk.ua_shop_kirpich-ogneupornyy_.html`, `utf-8`);
	let i = 0;
	while (++i < 10000) {
		let root = HTMLParser.parse(content);
		let name;
		const parent = Math.random().toString();
		try {
			name = root.querySelector(`.shop-categories__title`);
			if (!name) name = root.querySelector(`.headList h1`);
			// name = JSON.parse(JSON.stringify(name.text)).trim();
			// name = name.text.trim();
			name = name.text;
			if (!cat[parent]) {
				cat[parent] = {
					name: {},
				};
			}
			cat[parent][`name`][lang] = name;
		} catch (error) { console.error(error); }

		if (!name) {
			console.error(`not found name`);
		}
	}
})();
```

As a result, cloning `name = JSON.parse(JSON.stringify(name.text)).trim();` for 10,000 cycles showed stable memory consumption.

At the same time, writing data without cloning very quickly led to a memory overflow:
<--- Last few GCs --->

[4060:0x6199760]    48338 ms: Mark-sweep (reduce) 2046.5 (2066.4) -> 2046.2 (2065.6) MB, 13.0 / 0.0 ms  (+ 2.8 ms in 2 steps since start of marking, biggest step 2.7 ms, walltime since start of marking 17 ms) (average mu = 0.288, current mu = 0.226) final[4060:0x6199760]    48354 ms: Mark-sweep (reduce) 2046.5 (2065.6) -> 2046.2 (2065.6) MB, 11.0 / 0.0 ms  (+ 5.2 ms in 3 steps since start of marking, biggest step 2.8 ms, walltime since start of marking 17 ms) (average mu = 0.242, current mu = 0.182) final

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 ```
1: 0xa877f0 node::Abort() [node]
 2: 0x9abe29 node::FatalError(char const*, char const*) [node]
 3: 0xc6ea6e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xc6ede7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe38865  [node]
 6: 0xe3940c  [node]
 7: 0xe46d9b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xe49485 v8::internal::Heap::HandleGCRequest() [node]
 9: 0xdec3e7 v8::internal::StackGuard::HandleInterrupts() [node]
10: 0x1129283 v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(v8::internal::Isolate*, int, v8::internal::RegExp::CallOrigin, unsigned long*, v8::internal::Code, unsigned long*, unsigned char const**, unsigned char const**) [node]
11: 0x141bd6c v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, unsigned long, unsigned long) [node]
12: 0x38212b60768e 
```


So far, the quickest way to solve the problem is to clone the received text data. Thus, the variable loses its bound method references.I'll try to read your code this weekend.

**Comment by taoqf** [comment] 2021-03-23 02:11
OK, I will do more tests about this.

**Comment by taoqf** [comment] 2021-03-23 09:37
It is really strange, I tried several versions of node.js, it seems the same.
I think it is something wrong with module `he`, but could not find the reason. in that lib, it just does some string replacing.
anyway, I have do the clone thing in encoding. try the newest version, it may resolved in this case.

**Comment by taoqf** [comment] 2021-04-15 01:02
This issue may be resolved after v3.1.1. 
Sorry for replying late.

**Closed by taoqf** 2021-04-15 01:02 UTC

**Comment by taoqf** [comment] 2021-04-15 01:03
This issue may be resolved since v3.1.1. 
Sorry for replying late.

**Comment by nonara** [comment] 2021-09-28 23:41
Hi all. Do we know for certain that this is resolved? If not, I'd like to take a look into it.

**Comment by ergcode** [comment] 2021-09-28 23:52
> Hi all. Do we know for certain that this is resolved? If not, I'd like to take a look into it.

  "dependencies": {
    "node-html-parser": "^4.1.5"
  }

Sorry, I forgot to answer. Fixed issue, just ran tests. This request can be closed.

**Comment by nonara** [comment] 2021-09-29 00:29
Great! Thanks for the diligence!

**Comment by begyyal** [comment] 2025-02-16 21:18
I don't know if it's expected or not, I encounted similar case by to refer `Node.innerText`.
Though this happend in v6.1.12, also current latest v7.0.1 did.
But this was resolved by replacing `Node.innerText` to `HTMLElement.text`.

**Comment by ergcode** [comment] 2025-02-16 21:25
> I don't know if it's expected or not, I encounted similar case by to refer `Node.innerText`. Though this happend in v6.1.12, also current latest v7.0.1 did. But this was resolved by replacing `Node.innerText` to `HTMLElement.text`.

I haven't seen memory leaks on different sites for a long time.
Can you give an example using an html file (link) and brief work with selectors? It is advisable to wrap everything in a 10000+ cycle.

**Comment by begyyal** [comment] 2025-02-17 02:43
> I haven't seen memory leaks on different sites for a long time.
> Can you give an example using an html file (link) and brief work with selectors? It is advisable to wrap everything in a 10000+ cycle.

Perhaps this might relate some factors on the site because I tried to reproduce with replacing the site to sample site, but couldn't.
And sorry, I can't provide the site which happened the situation due to circumstances.

(As a side note, I recognized this by my application crashed at first.
I inspected the cause using `process.memoryUsage()`, therefore I reached this module.
In this situation, nodejs heapsize increase approximately 300mb to 3.5gb untile the app crashed after processing over 5000 pages for 2 hours.
But this was resolved by replacing `Node.innerText` to `HTMLElement.text`.
...and I confirmed cloning `innerText` string [`(" " + innerText).slice(1)`] is also efficiency in the test.)

**Comment by ergcode** [comment] 2025-02-17 09:01
> > I haven't seen memory leaks on different sites for a long time.
> > Can you give an example using an html file (link) and brief work with selectors? It is advisable to wrap everything in a 10000+ cycle.
> 
> Perhaps this might relate some factors on the site because I tried to reproduce with replacing the site to sample site, but couldn't. And sorry, I can't provide the site which happened the situation due to circumstances.
> 
> (As a side note, I recognized this by my application crashed at first. I inspected the cause using `process.memoryUsage()`, therefore I reached this module. In this situation, nodejs heapsize increase approximately 300mb to 3.5gb untile the app crashed after processing over 5000 pages for 2 hours. But this was resolved by replacing `Node.innerText` to `HTMLElement.text`. ...and I confirmed cloning `innerText` string [`(" " + innerText).slice(1)`] is also efficiency in the test.)

If you don't find the code section that causes the memory leak, take the body of the response, create worker_threads or child_process. Inside the sub-process, get the data and return it to the main process.
