### ISSUE TITLE
"SyntaxError: The requested module 'node-html-parser' does not provide an export named 'parse'"

### ISSUE THREAD

**Issue by Pomax** [taoqf/node-html-parser#160] opened 2021-10-03 00:55 UTC
Installed 4.1.5, running a project with `type: "module"` in package.json, and used the syntax `import { parse } from 'node-html-parser';` as per the README. Got this error.

**Comment by nonara** [comment] 2021-10-03 21:37
Thanks for the report. This is a duplicate of https://github.com/taoqf/node-html-parser/issues/139

I have a fix ready. Should be released shortly.

**Comment by Pomax** [comment] 2021-10-03 22:23
Nice! As a potentially breaking change, releasing it as a new major version's probably a good idea.

**Comment by nonara** [comment] 2021-10-03 22:49
Yep. That's the plan. Will post a comment in this thread when it's released.

**Closed** 2021-10-10 04:14 UTC
Labels: duplicate
